In [ ]:
from array import array

def cambiar_renglones(matriz, i, j):


    matriz = matriz[:]
    temp = array('f', matriz[j*3:j*3+3])
    for k in range(3):
        matriz[j*3+k] = matriz[i*3+k]
        matriz[i*3+k] = temp[k]
    return matriz

 Función para cambiar dos renglones de una matriz.

    Args:
    - matriz: matriz representada como un arreglo de 9 elementos.
    - i, j: índices de los renglones que se intercambiarán.

    Returns:
    - matriz: la matriz después de cambiar los renglones.
    

In [ ]:
def multiplicar_renglon(matriz, i, escalar):

    matriz = matriz[:]
    for k in range(i*3, i*3+3):
        matriz[k] *= escalar
    return matriz

 Función para multiplicar un renglón de la matriz por un escalar.

    Args:
    - matriz: matriz representada como un arreglo de 9 elementos.
    - i: índice del renglón que se multiplicará.
    - escalar: el escalar por el cual se multiplicará el renglón.

    Returns:
    - matriz: la matriz después de la multiplicación.

In [ ]:
def sumar_renglones(matriz, i, j, escalar=1):

    matriz = matriz[:]
    for k in range(3):
        matriz[i*3+k] += matriz[j*3+k]
    return matriz



    Función para sumar un múltiplo de un renglón a otro renglón.

    Args:
    - matriz: matriz representada como un arreglo de 9 elementos.
    - i, j: índices de los renglones que se sumarán.

    Returns:
    - matriz: la matriz después de la suma.
  

In [4]:
from array import array

def cambiar_renglones(matriz, i, j):
    matriz = matriz[:]
    temp = array('f', matriz[j*3:j*3+3])
    for k in range(3):
        matriz[j*3+k] = matriz[i*3+k]
        matriz[i*3+k] = temp[k]
    return matriz

def multiplicar_renglon(matriz, i, escalar):

    matriz = matriz[:]
    for k in range(i*3, i*3+3):
        matriz[k] *= escalar
    return matriz

def sumar_renglones(matriz, i, j, escalar=1):

    matriz = matriz[:]
    for k in range(3):
        matriz[i*3+k] += matriz[j*3+k] * escalar
    return matriz

#MATRIX ORIGINAL
h = array('f', [1.1, 2.2, 3.3,
                4.4, 5.5, 6.6,
                7.7, float('-inf'), float('nan')])

# Ejemplo de uso
# Cambiar el renglón 0 con el renglón 1
h1 = cambiar_renglones(h, 0, 1)
print("Matriz después de cambiar renglones 0 y 1:")
print(h1)
print()

# Multiplicar el renglón 2 por 1/3
h2 = multiplicar_renglon(h, 2, 5)
print("Matriz después de multiplicar el renglón 2 por 5:")
print(h2)
print()

# Sumar el renglón 1 al renglón 0
h3 = sumar_renglones(h, 0, 1)
print("Matriz después de sumar el renglón 1 al renglón 0:")
print(h3)

Matriz después de cambiar renglones 0 y 1:
array('f', [4.400000095367432, 5.5, 6.599999904632568, 1.100000023841858, 2.200000047683716, 3.299999952316284, 7.699999809265137, -inf, nan])

Matriz después de multiplicar el renglón 2 por 1/3:
array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432, 5.5, 6.599999904632568, 38.5, -inf, nan])

Matriz después de sumar el renglón 1 al renglón 0:
array('f', [5.5, 7.699999809265137, 9.899999618530273, 4.400000095367432, 5.5, 6.599999904632568, 7.699999809265137, -inf, nan])


In [1]:
import numpy as np
from sympy import Matrix

def cambiar_renglones(matriz, i, j):
    matriz = Matrix(matriz)
    matriz.row_swap(i, j)
    return matriz

def multiplicar_renglon(matriz, i, escalar):
    matriz = matriz.copy()
    matriz[i] = np.multiply(matriz[i], escalar)
    return matriz

def sumar_renglones(matriz, i, j, escalar=1):
    matriz = matriz.copy()
    matriz[i] = np.add(matriz[i], np.multiply(matriz[j], escalar))
    return matriz

# Matriz original
matriz_original = np.array([[1.1, 2.2, 3.3],
                             [4.4, 5.5, 6.6],
                             [7.7, float('-inf'), float('nan')]])

# Ejemplo de uso
# Cambiar el renglón 0 con el renglón 1
resultado_cambio_renglones = cambiar_renglones(matriz_original, 0, 1)
print("Matriz después de cambiar renglones 0 y 1:")
print(resultado_cambio_renglones)
print()

# Multiplicar el renglón 2 por 5
resultado_multiplicacion_renglon = multiplicar_renglon(matriz_original, 2, 5)
print("Matriz después de multiplicar el renglón 2 por 5:")
print(resultado_multiplicacion_renglon)
print()

# Sumar el renglón 1 al renglón 0
resultado_suma_renglones = sumar_renglones(matriz_original, 0, 1)
print("Matriz después de sumar el renglón 1 al renglón 0:")
print(resultado_suma_renglones)

Matriz después de cambiar renglones 0 y 1:
Matrix([[4.40000000000000, 5.50000000000000, 6.60000000000000], [1.10000000000000, 2.20000000000000, 3.30000000000000], [7.70000000000000, -oo, nan]])

Matriz después de multiplicar el renglón 2 por 5:
[[ 1.1  2.2  3.3]
 [ 4.4  5.5  6.6]
 [38.5 -inf  nan]]

Matriz después de sumar el renglón 1 al renglón 0:
[[ 5.5  7.7  9.9]
 [ 4.4  5.5  6.6]
 [ 7.7 -inf  nan]]


En el segmento anterior se hizo uso de la bliblioteca numpy y simpy para la comprobacion de la matriz.